name: "GitHub Repo Forked or Starred Notification"

on:
  # Runs your workflow when someone forks a repository.
  fork:
  # Runs your workflow when the workflow's repository is starred.
  # https://docs.github.com/cn/github-ae@latest/actions/using-workflows/events-that-trigger-workflows#watch
  watch:
    types: [started]

env:
  EVENT_NAME: "EVENT_NAME"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'fork' }}
        run: echo "🎉 triggered by a ${{ github.event_name }} event."
        env:
          EVENT_NAME: "forked"
          run: echo "$EVENT_NAME event."
      - if: ${{ github.event_name == 'watch' }}
        run: echo "🎉 triggered by a ${{ github.event_name }} event."
        env:
          EVENT_NAME: "starred"
          run: echo "$EVENT_NAME event."

      - name: "Checkout codes"
        uses: actions/checkout@v1
      - name: "Send mail"
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_USERPASSORD }}
          subject: Github repo has been ${{env.EVENT_NAME}}ed!
          # this github.event_name is watch or fork
          body: "Your repo [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}) was ${{env.EVENT_NAME}}ed by ${{ github.actor }}"
          to: tisfeng@gmail.com
          from: GitHub Actions
          convert_markdown: true
