name: "GitHub Repo Starred or Forked Notification"

on:
  # Runs your workflow when someone forks a repository.
  fork:
  # Runs your workflow when the workflow's repository is starred.
  # https://docs.github.com/cn/github-ae@latest/actions/using-workflows/events-that-trigger-workflows#watch
  watch:
    types: [started]

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'fork' }}
        run: |
          echo "🎉 triggered by a ${{ github.event_name }} event."
          echo "event_name=forked" >> $GITHUB_ENV
      - if: ${{ github.event_name == 'watch' }}
        run: |
          echo "🎉 triggered by a ${{ github.event_name }} event."
          echo "event_name=starred" >> $GITHUB_ENV

      - name: Get repository information
        run: |
          result=$(curl -H "Authorization: token ${{ secrets.MY_TOKEN }}"  "https://api.github.com/repos/${{ github.repository }}")
          stars=$(echo $result | jq '.stargazers_count')
          repo_name=$(echo $result | jq '.name')
          echo "Number of stars: $stars"
          # save the value to env
          echo "repo_stars=$stars" >> $GITHUB_ENV
          echo "repo_name=$repo_name" >> $GITHUB_ENV

      - name: Convert body to HTML
        run: |
          html_body=$(cat << EOM
                      <h1>${{env.repo_name}}</h1> 
                      <p><img src='https://raw.githubusercontent.com/tisfeng/ImageBed/main/uPic/icon_512x512-1671278252.png' width='128'> </p>
                      <p>Your repo <a href='${{ github.server_url }}/${{ github.repository }}'>${{ env.repo_name }}</a> has <b>${{env.event_name}}</b> ✨ by <b><a href='${{ github.server_url }}/${{ github.actor }}'>${{ github.actor }}</a></b></p>
                      <p>Total stars: <b>${{env.repo_stars}}</b></p>
                      <p>Stargazers list: <a href='${{ github.server_url }}/${{ github.repository }}/stargazers'>${{ github.repository }}/stargazers</a></p>
                      EOM)

          echo "html_body=$html_body" >> $GITHUB_ENV
          echo "html body: ${{env.html_body}}"

      - name: "Send mail"
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_BOT_USERNAME }}
          password: ${{ secrets.GMAIL_BOT_PASSWORD }}
          subject: ✨ GitHub repo has been ${{env.event_name}}!
          # List stargazers  https://github.com/tisfeng/Raycast-Easydict/stargazers
          html_body: ${{env.html_body}}
          to: ${{ secrets.RECEIVER_EMAIL }}
          from: GitHub Actions
